### ISSUE TITLE
merge-weights.py fails merging the 13B model

### ISSUE THREAD

**Issue by teknoraver** [randaller/llama-chat#8] opened 2023-03-10 15:03 UTC
```
matteo@llama:~/llama-chat$ python3 merge-weights.py --input_dir ../LLaMA --model_size 13B
Traceback (most recent call last):
  File "merge-weights.py", line 168, in <module>
    main()
  File "merge-weights.py", line 163, in main
    model_size=args.model_size,
  File "merge-weights.py", line 95, in write_model
    f"layers.{layer_i}.ffn_norm.weight": loaded[0][f"layers.{layer_i}.ffn_norm.weight"],
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
```

**Comment by teknoraver** [comment] 2023-03-10 15:24
happens with 30B too

**Comment by randaller** [comment] 2023-03-10 15:47
Duplicate of #4

**Closed by randaller** 2023-03-10 15:47 UTC
